### ISSUE TITLE
当一个节点挂了比较长的时间或者向一个replicat set里面新增一个节点，数据是如何同步的

### ISSUE THREAD

**Issue by superwood** [XiaoMi/pegasus#1]
当一个节点挂了比较长的时间，重新复活后数据是如何同步的？

**Comment by shengofsun** [comment]
在pegasus里这一过程叫做learn。
简单概括下过程：replica set中每个副本都会保存自己commit到WAL的哪一条了，然后开始向leader汇报。leader根据副本所在的点，来决定是要拷贝数据库checkpoint，还是要拷贝增量log，还是要把内存缓存拷贝过去。这几个阶段也不是完全互斥的，有可能是接力的过程(先checkpoint, 再log, 再内存缓存)。

几个比较关键的点是：
1. 拷贝log时怎样做到高效。这个在[设计与实现](https://github.com/XiaoMi/pegasus/wiki/%E8%AE%BE%E8%AE%A1%E4%B8%8E%E5%AE%9E%E7%8E%B0#sharedlog%E5%92%8Cprivatelog)里强调过，每个副本都有自己的private log。
2. 副本在向leader追数据的时候，leader可能也在接受写。所以在同步到某个阶段时，leader会开始把自己最新收到的数据一起发送给副本。
3. 同步的过程需要限流别把集群搞崩

整个过程中，为了把数据拷完整，细节还是比较微妙的。这个就只能看代码了：[replica_learn.cpp](https://github.com/XiaoMi/rdsn/blob/3c3541f48dee15936422b5533f9be556de05edf8/src/dist/replication/lib/replica_learn.cpp)

如果真对pegasus感兴趣，强烈建议先看PacificA的论文。欢迎PR :-)

**Comment by Allianzcortex** [comment]
@shengofsun 有机会的时候看一下，好像蛮有趣的，用 PacificA 做的还是少。第一眼的时候以为在用 zk 。
