### ISSUE TITLE
能简要的描述下数据分片分裂、动态扩容实现的思路吗？

### ISSUE THREAD

**Issue by scottzzq** [XiaoMi/pegasus#10]
如题，感觉整个过程还是比较复杂的。多谢！

**Comment by shengofsun** [comment]
下周就写，写好加到文档里，敬请期待

**Comment by shengofsun** [comment]
@scottzzq 可以加入到我们的[slack讨论群](https://join.slack.com/t/pegasus-kv/shared_invite/enQtMjcyMjQzOTk4Njk1LWVkMjlkMGE5Mzg1Y2M3MDc0NGYyYzQ5YzYyMGE0ZjlhMDMyNjU1ZGViYzdjZmUwNjVmNGE0ZDdkMWJiN2Q1MDY)

**Comment by sunwsh** [comment]
同样期待，这周开始看这个pegasus系统，也想了解这个，这两天就看代码，还没找到。

**Comment by qinzuoyan** [comment]
https://github.com/XiaoMi/rdsn/issues/69
