### ISSUE TITLE
Fault injection on write path

### ISSUE THREAD

**Issue by neverchanje** [XiaoMi/pegasus#109]
We can add random fault injection on `pegasus_write_service::impl::db_write` to test the condition where rocksdb is failed.

**Comment by qinzuoyan** [comment]
also consider adding fail_qps counters

**Comment by neverchanje** [comment]
The fail point lib is added by [util: add fail point implementation (#120)](https://github.com/XiaoMi/rdsn/commit/87d5bc2e6ab59510f069c6f3e2febc36d7eced3c)
