### ISSUE TITLE
Did pegasus support distributed transaction?

### ISSUE THREAD

**Issue by kewei-wang** [XiaoMi/pegasus#11]
just like the issue title,did it support distributed transaction so I can use it like the following code?
```java
pegasus.beginTransaction();
pegasus.put("key",value);
v = pegasus.get("key");
v++;
pegasus.put("key",v);
pegasus.commit();
```

**Comment by shengofsun** [comment]
@kowayvwang currently we don't support distributed transaction. the only guarantee we can give is that multiple put operations of sortkeys **on the same hashkey** are atomic. 
that is to say, if you write code like this: 
```
pegasus.multi_set("aa", [("bb", "cc"), ("dd", ee), ("ff" -> "gg") ...])
```
the operations of "aa:bb -> cc" & "aa:dd -> ee" & "aa:ff" -> "gg" will all success or all fail.
