### ISSUE TITLE
“#pragma once“ usage is not recommended 

### ISSUE THREAD

**Issue by mcgrady-forever** [XiaoMi/pegasus#119]
I saw "#pragma once" in header file, it is better use "#ifndef XXX #define XXX ... # endif"

**Comment by neverchanje** [comment]
I'm not sure if there's any place documents about the downside of `pragma once`. The google-code-style of C++ warns only for the windows developer to prohibit the use of it (https://google.github.io/styleguide/cppguide.html#Windows_Code), not for linux. Linux is the platform pegasus only supports.

**Comment by mcgrady-forever** [comment]
The latter usage is more compatible, some platform not support "#pragma once", most open source projects do not use that either

**Comment by neverchanje** [comment]
I'm pretty sure `#pragma once`  is well supported by both gcc(after 4.8) and clang, and rocksdb uses it too.

**Comment by qinzuoyan** [comment]
Thanks for discussion. Now we will keep using ```#pragma once``` unless there is a solid reason to change it.

**Comment by mcgrady-forever** [comment]
Thanks for reply
