### ISSUE TITLE
编译thrift失败

### ISSUE THREAD

**Issue by zhanglistar** [XiaoMi/pegasus#14]
系统：ubuntu16.04

➜  thirdparty git:(dc3a3ee) ✗ ./build-thirdparty.sh 
+++ dirname ./build-thirdparty.sh
++ cd .
++ pwd
+ TP_DIR=/home/listar/Code/pegasus/rdsn/thirdparty
+ TP_SRC=/home/listar/Code/pegasus/rdsn/thirdparty/src
+ TP_BUILD=/home/listar/Code/pegasus/rdsn/thirdparty/build
+ TP_OUTPUT=/home/listar/Code/pegasus/rdsn/thirdparty/output
+ export CC=gcc
+ CC=gcc
+ export CXX=g++
+ CXX=g++
+ CLEAR_OLD_BUILD=NO
+ BOOST_ROOT=
+ [[ 0 > 0 ]]
+ '[' NO = YES ']'
+ mkdir -p /home/listar/Code/pegasus/rdsn/thirdparty/output/include
+ mkdir -p /home/listar/Code/pegasus/rdsn/thirdparty/output/lib
+ mkdir -p /home/listar/Code/pegasus/rdsn/thirdparty/output/bin
+ '[' '!' -d /home/listar/Code/pegasus/rdsn/thirdparty/output/include/concurrentqueue ']'
+ echo 'skip build concurrentqueue'
skip build concurrentqueue
+ '[' '!' -d /home/listar/Code/pegasus/rdsn/thirdparty/output/include/gtest ']'
+ echo 'skip build gtest'
skip build gtest
+ '[' '!' -d /home/listar/Code/pegasus/rdsn/thirdparty/output/include/rapidjson ']'
+ '[' '!' -d /home/listar/Code/pegasus/rdsn/thirdparty/output/include/thrift ']'
+ mkdir -p /home/listar/Code/pegasus/rdsn/thirdparty/build/thrift-0.9.3
+ cd /home/listar/Code/pegasus/rdsn/thirdparty/build/thrift-0.9.3
+ CMAKE_FLAGS='-DCMAKE_BUILD_TYPE=release        -DWITH_JAVA=OFF        -DWITH_PYTHON=OFF        -DWITH_C_GLIB=OFF        -DWITH_CPP=ON        -DBUILD_TESTING=OFF        -DBUILD_EXAMPLES=OFF        -DWITH_QT5=OFF        -DWITH_QT4=OFF        -DWITH_OPENSSL=OFF        -DBUILD_COMPILER=OFF        -DBUILD_TUTORIALS=OFF        -DWITH_LIBEVENT=OFF        -DCMAKE_INSTALL_PREFIX=/home/listar/Code/pegasus/rdsn/thirdparty/output        -DCMAKE_POSITION_INDEPENDENT_CODE=ON        -DWITH_SHARED_LIB=OFF'
+ '[' x '!=' x ']'
+ echo -DCMAKE_BUILD_TYPE=release -DWITH_JAVA=OFF -DWITH_PYTHON=OFF -DWITH_C_GLIB=OFF -DWITH_CPP=ON -DBUILD_TESTING=OFF -DBUILD_EXAMPLES=OFF -DWITH_QT5=OFF -DWITH_QT4=OFF -DWITH_OPENSSL=OFF -DBUILD_COMPILER=OFF -DBUILD_TUTORIALS=OFF -DWITH_LIBEVENT=OFF -DCMAKE_INSTALL_PREFIX=/home/listar/Code/pegasus/rdsn/thirdparty/output -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DWITH_SHARED_LIB=OFF
-DCMAKE_BUILD_TYPE=release -DWITH_JAVA=OFF -DWITH_PYTHON=OFF -DWITH_C_GLIB=OFF -DWITH_CPP=ON -DBUILD_TESTING=OFF -DBUILD_EXAMPLES=OFF -DWITH_QT5=OFF -DWITH_QT4=OFF -DWITH_OPENSSL=OFF -DBUILD_COMPILER=OFF -DBUILD_TUTORIALS=OFF -DWITH_LIBEVENT=OFF -DCMAKE_INSTALL_PREFIX=/home/listar/Code/pegasus/rdsn/thirdparty/output -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DWITH_SHARED_LIB=OFF
+ cmake /home/listar/Code/pegasus/rdsn/thirdparty/src/thrift-0.9.3 -DCMAKE_BUILD_TYPE=release -DWITH_JAVA=OFF -DWITH_PYTHON=OFF -DWITH_C_GLIB=OFF -DWITH_CPP=ON -DBUILD_TESTING=OFF -DBUILD_EXAMPLES=OFF -DWITH_QT5=OFF -DWITH_QT4=OFF -DWITH_OPENSSL=OFF -DBUILD_COMPILER=OFF -DBUILD_TUTORIALS=OFF -DWITH_LIBEVENT=OFF -DCMAKE_INSTALL_PREFIX=/home/listar/Code/pegasus/rdsn/thirdparty/output -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DWITH_SHARED_LIB=OFF
-- Parsed Thrift package version: 0.9.3
-- Parsed Thrift version: 0.9.3 (0.9.3)
-- Building without tests
-- ----------------------------------------------------------
-- Thrift version:                       0.9.3 (0.9.3)
-- Thrift package version:               0.9.3
-- Build configuration Summary
--   Build Thrift compiler:              OFF
--   Build with unit tests:              OFF
--   Build examples:                     OFF
--   Build Thrift libraries:             ON
--  Language libraries:
--   Build C++ library:                  OFF
--    - Boost headers missing
--   Build C (GLib) library:             OFF
--    - Disabled by via WITH_C_GLIB=OFF
--   Build Java library:                 OFF
--    - Disabled by via WITH_JAVA=OFF
--    - Ant missing
--   Build Python library:               OFF
--    - Disabled by via WITH_PYTHON=OFF
--  Library features:
--   Build shared libraries:             OFF
--   Build static libraries:             ON
--   Build with ZLIB support:            ON
--   Build with libevent support:        OFF
--   Build with Qt4 support:             OFF
--   Build with Qt5 support:             OFF
--   Build with OpenSSL support:         OFF
--   Build with Boost thread support:    OFF
--   Build with C++ std::thread support: OFF
-- ----------------------------------------------------------
-- Configuring done
-- Generating done
-- Build files have been written to: /home/listar/Code/pegasus/rdsn/thirdparty/build/thrift-0.9.3
+ make -j8
+ make install
make: *** No rule to make target 'install'。 停止。
+ res=2
+ cd /home/listar/Code/pegasus/rdsn/thirdparty
+ exit_if_fail thrift 2
+ '[' 2 -ne 0 ']'
+ echo 'build thrift failed'
build thrift failed
+ exit 2
➜  thirdparty

## 分析
找到原因了，是boost版本太老导致，系统中并存了2个版本，1个版本太老是1.44版本，删除了就ok了。

**Comment by qinzuoyan** [comment]
gdb和cmake的版本号都是多少？

**Comment by zhanglistar** [comment]
找到原因了，是boost版本太老导致，系统中并存了2个版本，1个版本太老是1.44版本，删除了就ok了。
