### ISSUE TITLE
benchmark test on v1.10.0

### ISSUE THREAD

**Issue by qinzuoyan** [XiaoMi/pegasus#148]
just like: [Benchmark on v1.8.0](https://github.com/XiaoMi/pegasus/wiki/Benchmark#benchmark-on-v180)

增加一项：
(5)数据只读: 12客户端*100线程

**Comment by zhangyifan27** [comment]
[Benchmark on v1.10.0](https://github.com/XiaoMi/pegasus/wiki/Benchmark#benchmark-on-v1100)
