### ISSUE TITLE
scan may have bug when primary switches

### ISSUE THREAD

**Issue by shengofsun** [XiaoMi/pegasus#156]
1. say a partition: [A(primary), B(secondary), C(secondary)]
2. Client X starts a scan operation, then an context id **C1** is generated and assigned to X
3. then the primary switch to B
4. Client Y starts another scan operation, accidenty the same context id **C1** is generated and assigned to Y
5. Client X continues its scanning with **C1**, but now the message is sent to B. However, "C1 of B" has assigned to another scan context. So the scan operation from X will get wrong data.

A possible fix may encode service_node's rpc_address to the "scan_context", so as to ensure every "context" is unique.

**Comment by qinzuoyan** [comment]
now that `context_id` is int64, we can add some mask in it, for example, use `server_start_time` or `random_int32` as the high 32 bits.

**Comment by shengofsun** [comment]
resolved
