### ISSUE TITLE
return ERR_HANDLER_NOT_FOUND if rpc code not exist on server

### ISSUE THREAD

**Issue by qinzuoyan** [XiaoMi/pegasus#162]
refer to code at [rpc_engine.cpp:618](https://github.com/XiaoMi/rdsn/blob/9bd165b312a648c4a0f4eb6620d87a7409e4d60c/src/core/core/rpc_engine.cpp#L618):
```c++
    if (code != ::dsn::TASK_CODE_INVALID) {
        ... ...
    } else {
        dwarn("recv message with unknown rpc name %s from %s, trace_id = %016" PRIx64,
              msg->header->rpc_name,
              msg->header->from_address.to_string(),
              msg->header->trace_id);

        dassert(msg->get_count() == 0, "request should not be referenced by anybody so far");
        delete msg;
    }
```

if rpc code is not exist on server, then server will ignore the request, which make client timeout.

I think `timeout` is not proper, it's better to get `ERR_HANDLER_NOT_FOUND` error.

**Comment by shengofsun** [comment]
closed as resolved
