### ISSUE TITLE
learn_app_concurrent_count inconsistent bug

### ISSUE THREAD

**Issue by qinzuoyan** [XiaoMi/pegasus#165]
learn_app_concurrent_count's increment and decrement may be not matched, which causes learn_app_concurrent_count inconsistent, and makes learning blocked:
```
W2018-08-15 16:42:44.772 (1534322564772409072 206e2) replica.replica6.0405000600000122: replica_learn.cpp:676:on_learn_reply(): 43.1@10.38.166.24:31801: on_learn_reply[0000004700000002]: learnee = 10.38.162.236:31801, exceed learn_app_max_concurrent_count(5) limit, skip this round
```

The reason is:
1. some replica is learning app after increment learn_app_concurrent_count
2. meta server disconnected
3. the replica status changes to INACTIVE by replica::on_meta_server_disconnected()
4. but the learn_app_concurrent_count is not decrement

**Comment by shengofsun** [comment]
closed as resolved
