### ISSUE TITLE
pegasus server core dumped after scanned by nmap 

### ISSUE THREAD

**Issue by sunwsh** [XiaoMi/pegasus#186]
我们在几台新的服务器上准备部署pegasus，运行一天多就会有个进程core ， 而且是没有业务请求情况下。  replica 进程和 meta 进程都会core dump。
core 文件名称： core-replica.asio.3-6001-1538262177 
                             core-meta.asio.1-29423-1538372576
![image](https://user-images.githubusercontent.com/4278126/46605187-3ea78b80-cb2b-11e8-9d53-f58d58c92f10.png)

备注：
1.  部署了3台服务器，每台一个meta进程，一个replica进程，一个zookeeper进程。
2. 程序core dump 时log 文件无异常。
3. gcc --version    gcc (Ubuntu 5.4.0-6ubuntu1~16.04.2) 5.4.0 20160609
    cat /etc/issue     Ubuntu 16.04 LTS \n \l
4. pegasus 版本：v1.11.1

这个是一个meta server 进程core dump时的记录，这个程序一直在slave，没有抢到zk 锁。
![image](https://user-images.githubusercontent.com/4278126/46642439-d055de00-cba9-11e8-912a-0c5f654c4b9d.png)

5. 用端口扫描工具nmap测试
   用端口扫描脚本测试，必现：  nmap -sT -p 1-65535 ip

**Comment by neverchanje** [comment]
另外麻烦提供一下 gcc 的版本

**Comment by sunwsh** [comment]
<img width="1056" alt="image" src="https://user-images.githubusercontent.com/4278126/46606880-74e80980-cb31-11e8-8b48-2a6516e1b62d.png">

**Comment by sunwsh** [comment]
<img width="1056" alt="image" src="https://user-images.githubusercontent.com/4278126/46606912-95b05f00-cb31-11e8-9feb-c1f2371cdd02.png">

![image](https://user-images.githubusercontent.com/4278126/46606943-a660d500-cb31-11e8-8a8d-110ef543d58c.png)

**Comment by neverchanje** [comment]
Reproducing scenario:

```
➜  pegasus git:(dup) ✗ ./run.sh start_onebox -r 3 -m 1
ERROR: some onebox processes are running, start failed
➜  pegasus git:(dup) ✗ ./run.sh list_onebox
mi       24506  1438  0 18:53 pts/28   00:00:00 /home/mi/git/pegasus/onebox/meta1/pegasus_server config.ini -app_list meta
mi       24517  1438  0 18:53 pts/28   00:00:00 /home/mi/git/pegasus/onebox/replica1/pegasus_server config.ini -app_list replica
mi       24595  1438  0 18:53 pts/28   00:00:00 /home/mi/git/pegasus/onebox/replica2/pegasus_server config.ini -app_list replica
mi       24701  1438  0 18:53 pts/28   00:00:00 /home/mi/git/pegasus/onebox/replica3/pegasus_server config.ini -app_list replica
➜  pegasus git:(dup) ✗ nmap -sT -p 34601 127.0.0.1

Starting Nmap 6.40 ( http://nmap.org ) at 2018-10-09 18:55 CST
Nmap scan report for localhost (127.0.0.1)
Host is up (0.000033s latency).
PORT      STATE SERVICE
34601/tcp open  unknown

Nmap done: 1 IP address (1 host up) scanned in 0.03 seconds
➜  pegasus git:(dup) ✗ ./run.sh list_onebox
mi       24517  1438  0 18:53 pts/28   00:00:00 /home/mi/git/pegasus/onebox/replica1/pegasus_server config.ini -app_list replica
mi       24595  1438  0 18:53 pts/28   00:00:00 /home/mi/git/pegasus/onebox/replica2/pegasus_server config.ini -app_list replica
mi       24701  1438  0 18:53 pts/28   00:00:00 /home/mi/git/pegasus/onebox/replica3/pegasus_server config.ini -app_list replica
➜  pegasus git:(dup) ✗ cd onebox/meta1                
➜  meta1 git:(dup) ✗ ls
config.ini  core  data  pegasus_server  result  zoo.log
```

**Comment by shengofsun** [comment]
看样子是抛了个异常没有catch?

**Comment by shengofsun** [comment]
@neverchanje 另外你看下，为啥那边的coredump堆栈信息很少，你这边就这么详细？

**Comment by neverchanje** [comment]
And I found this issue (https://github.com/cpp-netlib/cpp-netlib/issues/677) from cpp-netlib having the same problem with us

**Comment by neverchanje** [comment]
@sunwsh you can cherry-pick this commit after it being accepted.

**Comment by sunwsh** [comment]
我试过你的修改，确实修复了，发nmap 时确实在哪里打印log ，
tcpdump -i eth0 host <ip> and port 34600 -vvv
我用tcpdump 对 nmap 的行为分析了一下，先 tcp连接，然后发包，然后马上发rst 断开连接。  所以确实可能出现，accept 后，处理时又断开了。
你现在 的修改只是减少概率了，感觉还不能彻底避免，感觉还是应该在这里增加try catch

**Comment by neverchanje** [comment]
:+1:能修复问题就好说
