### ISSUE TITLE
基于Hash的partition的调度

### ISSUE THREAD

**Issue by xieyilun** [XiaoMi/pegasus#2]
我看到你们在微信上的文章，partition的调度使用了网络流算法，正好我以前针对这个问题做过一个费用流的算法，目标里包括了分机架和总迁移量尽量小，感兴趣的话可以参考一下。

http://www.jianshu.com/p/686b55e2f96b

**Comment by shengofsun** [comment]
多谢提建议，partition的调度我们后期会继续优化，我也想过费用流的模型，你的算法我也会仔细学习:-) 
后面假如真用你算法了，是不是直接在代码里附上链接就好?

**Comment by xieyilun** [comment]
可以

**Comment by shengofsun** [comment]
resolved
