### ISSUE TITLE
测试两副本配置（一主一备）的写吞吐性能提升

### ISSUE THREAD

**Issue by qinzuoyan** [XiaoMi/pegasus#207]
Pegasus目前推荐是三副本配置（一主两备），吞吐不太理想。
一种可选方案是降级为一主一备，能够降低机器负载，减少RPC交互次数，提升吞吐。
需要对这两种配置进行性能对比。

**Comment by neverchanje** [comment]
集群包含5个ReplicaServer节点(使用1.11.1版本)，表分为64个Partition

# ​2 备份，单条数据 20KB

​测试Case | ​读写比(读 : 写) | ​运行时间(小时) | ​读QPS(条/秒​) | ​读平均延迟(微​秒) | ​读P99延迟(微秒) | ​写QPS​(条/秒​) | ​写平均延迟(微秒) | ​写P99延迟(微秒)
-- | -- | -- | -- | -- | -- | -- | -- | --
​(1) 数据加载 - 3客户端，每个10线程 | ​​0 : 1 | 0.98 | ​- | ​- | ​- | ​8454 | 3543 | ​30527
​(2) ​数据读写 - 3客户端，每个15线程 | ​1 : 3 | 0.82 | 2553​ | 4109 | 36991 | 7664 | 4480 | ​66367
​(3) 数据读写 - 3客户端，每个30线程 | ​30 : 1​ | 1.31 | 61561​ | 1398 | 17215 | 2051 | 1667 | 6955
​(4) 数据只读 - 6客户端，每个100线程 | 1 : 0​​ | ​0.86 | 966​80 | ​3098 | ​13247 | ​- | -​ | ​-

# ​3 备份，单条数据 20KB


​测试Case | ​读写比(读 : 写) | ​运行时间(小时) | ​读QPS(条/秒​) | ​读平​均延迟(微​秒) | ​读P99延迟(微秒) | ​写QPS​(条/秒​) | ​写平均延迟(微秒) | ​写P99延迟(微秒)
-- | -- | -- | -- | -- | -- | -- | -- | --
​(1) 数据加载 - 3客户端，每个10线程 | ​​0 : 1 | 1.40​​ | ​- | ​- | ​- | ​5919​ | 5063 | ​40639
​(2) ​数据读写 - 3客户端，每个15线程 | ​1 : 3 | ​1.11 | 1876 | 6927 | 44639 | 5632 | 5612 | ​76095
​(3) 数据读写 - 3客户端，每个30线程 | ​30 : 1​ | 1.63 | 49341 | 1751 | 21615 | 1644 | 1935 | 11159
​(4) 数据只读 - 6客户端，每个100线程 | 1 : 0​​ | 1.09​ | 76368 | ​3923 | ​15679 | ​- | -​ | ​-

**RocsDB配置**

```
    rocksdb_abnormal_get_time_threshold_ns = 10000000
    rocksdb_abnormal_get_size_threshold = 1000000
    rocksdb_abnormal_multi_get_time_threshold_ns = 100000000
    rocksdb_abnormal_multi_get_size_threshold = 10000000
    rocksdb_abnormal_multi_get_iterate_count_threshold = 1000
    rocksdb_write_buffer_size = 67108864
    rocksdb_max_write_buffer_number = 6
    rocksdb_max_background_flushes = 4
    rocksdb_max_background_compactions = 12
    rocksdb_num_levels = 6
    rocksdb_target_file_size_base = 67108864
    rocksdb_target_file_size_multiplier = 1
    rocksdb_max_bytes_for_level_base = 671088640
    rocksdb_max_bytes_for_level_multiplier = 10
    rocksdb_level0_file_num_compaction_trigger = 4
    rocksdb_level0_slowdown_writes_trigger = 30
    rocksdb_level0_stop_writes_trigger = 60
    rocksdb_disable_table_block_cache = false
    rocksdb_compression_type = none
```

**replication 配置**
```
    prepare_timeout_ms_for_secondaries = 3000 10000 
    prepare_timeout_ms_for_potential_secondaries = 5000 10000
    log_shared_file_count_limit = 100 200
```

**Usage Scenario**
```  
    prefer_write
```

​
