### ISSUE TITLE
Question about reconfiguration mechanism in Pegasus

### ISSUE THREAD

**Issue by lorneli** [XiaoMi/pegasus#21]
Hi I'm getting started with Pegasus by reading PacificA consensus algorithm.

In the paper, primary/secondary data node could suspect its peer has become faulty,
then it reports to configuration manager. 

After the configuration manager removes the faulty one, the replica count in this 
replication group has been reduced.

In Pegasus's implementation, does the configuration manager pick up a new node and 
add it to this replication group automatically? Or do this via some tools?

Thanks in advance.

**Comment by neverchanje** [comment]
yes. meta server (aka configuration manager) will handle this.
See this https://github.com/XiaoMi/pegasus/wiki/%E8%AE%BE%E8%AE%A1%E4%B8%8E%E5%AE%9E%E7%8E%B0#replicaserver%E7%9A%84%E7%AE%A1%E7%90%86.

**Comment by qinzuoyan** [comment]
Yes, automatically.

**Comment by lorneli** [comment]
@neverchanje @qinzuoyan  Thanks. Haven't noticed the wiki page:see_no_evil:
