### ISSUE TITLE
Support check if the cluster is balanced

### ISSUE THREAD

**Issue by qinzuoyan** [XiaoMi/pegasus#237]
* in meta-server, check if the cluster is balanced, and add related perf-counter
* in shell, show if the cluster is balanced for `cluster_info` command

**Comment by mentoswang** [comment]
### Balance Score
- 仅在允许做balance的条件下进行评分, 分数为balance的作用程度, 如果集群有app unhealthy时, score = 0
- returned by lb(only glb for now).balance, score =
  - balance_checker = true: 整理balance的操作数，包含
    - 所有app的move_pri, 即使balancer_in_turn = true
    - 所有app的copy_pri, 即使only_move_primary = true
    - 所有app的copy_sec, 即使only_primary_balancer = true
  - balance_checker = false: 本轮balance的操作数
- steady level下只做balance(balance_checker = true)
- lively level下先做balance(balance_checker = true), 如果返回操作数 != 0则做balance(balance_checker = false)
- 其他load_balancer, score = 0
### Perf Counter
- 在balance(balance_checker = true)之后更新
### cluster_info
- get from server_state
![2018-12-29 12-15-12](https://user-images.githubusercontent.com/40587846/50533423-08930a00-0b64-11e9-9d93-eb3c590f01dd.png)
