### ISSUE TITLE
build failed on centos 7.2

### ISSUE THREAD

**Issue by clicx** [XiaoMi/pegasus#280]
Build succeed
INFO: start build rocksdb...
WARNING_ALL=NO
ENABLE_GCOV=NO
BUILD_TYPE=release
Building...
RUN_VERBOSE=NO
make: *** No rule to make target `install'.  Stop.
ERROR: build rocksdb failed

**Comment by qinzuoyan** [comment]
你用的哪个分支编译的？试试checkout到master分支？
另外你的CMake版本是多少？

**Comment by clicx** [comment]
#git branch
* master
#cmake --version
cmake version 2.8.12.2

**Comment by qinzuoyan** [comment]
你用 `./run.sh build -c -v` 重新编译一遍，看看报错是什么？

**Comment by clicx** [comment]
Thanks, now build successfully after changed the command that you provided.
