### ISSUE TITLE
onebox集群，停止调某个replica进程后，通过shell进行数据操作报ERROR:timeout

### ISSUE THREAD

**Issue by jackeylove01** [XiaoMi/pegasus#327]
体验 `onebox` 集群，通过 `shell` 进行数据操作。创建一个新的表后，执行数据操作没有问题，然后运行  `./run.sh stop_onebox_instance -r <id>` 命令，或者直接 `kill`调 `replica` 进程后，再次执行数据操作，就会报错`ERROR：timeout`。

![2019-05-12 16-37-23 的屏幕截图](https://user-images.githubusercontent.com/50524485/57579920-f9d73f00-74d5-11e9-882a-82c6d34f5b37.png)

![2019-05-12 16-38-22 的屏幕截图](https://user-images.githubusercontent.com/50524485/57579954-808c1c00-74d6-11e9-9153-2b387d250112.png)

![2019-05-12 16-44-24 的屏幕截图](https://user-images.githubusercontent.com/50524485/57579942-576b8b80-74d6-11e9-9235-6ee72b595e81.png)

![2019-05-12 16-39-22 的屏幕截图](https://user-images.githubusercontent.com/50524485/57579941-50dd1400-74d6-11e9-8fc7-c6b7378277cf.png)

![2019-05-12 16-51-01 的屏幕截图](https://user-images.githubusercontent.com/50524485/57579983-bf21d680-74d6-11e9-88ef-c0a467b8d22e.png)

以上为运行的截图，麻烦帮忙看下什么问题，thanks~

**Comment by neverchanje** [comment]
Because there is no primary replica alive for partition 3 (your pic 5), you must wait for new primary elected to be able to read/write.

**Comment by jackeylove01** [comment]
But I've been waiting for at least ten minutes, and I still can't do data manipulation.I don't think it's normal.

**Comment by jackeylove01** [comment]
> Because there is no primary replica alive for partition 2 (your pic 5), you must wait for new primary elected to be able to read/write. Normally it doesn't take long.
> 
> Btw we suggest to use [v1.11.3](https://github.com/XiaoMi/pegasus/releases/tag/v1.11.3) which is the latest stable version.

But I've been waiting for at least ten minutes, and I still can't do data manipulation.I don't think it's normal.

**Comment by zhangyifan27** [comment]
由于只剩下了2个replica server（图3），而create建表是默认三副本的，一个replica server挂掉后partition 2没有primary所以无法读写（图5）。

可以用start_onebox -r 指定replica个数，启动多个（大于3）replica server，再stop其中一个试试。

**Comment by jackeylove01** [comment]
> 由于只剩下了2个replica server（图3），而create建表是默认三副本的，一个replica server挂掉后partition 2没有primary所以无法读写（图5）。
> 
> 可以用start_onebox -r 指定replica个数，启动多个（大于3）replica server，再stop其中一个试试。

我尝试了，你说的是对的，我再学习一下，感谢。

**Comment by neverchanje** [comment]
@zhangyifan27 is wrong.
@jackeylove01 

This behavior is controlled by a configuration item of meta server:
```
[meta_server]
min_live_node_count_for_unfreeze = 3
```

If only 2 servers alive at last, the cluster will turn into a "freeze" state, which means
some of the partitions may not gonna have its primary, and the cluster will become
unavailable.

```
>>> app temp -d
[Parameters]
app_name  : temp
detailed  : true

[Result]
app_name           : temp
app_id             : 1   
partition_count    : 8   
max_replica_count  : 3   
details            :     
pidx  ballot  replica_count  primary              secondaries                                
0     3       3/3            0.0.0.0:34803  [0.0.0.0:34801,0.0.0.0:34802]  
1     4       2/3            -              [0.0.0.0:34802,0.0.0.0:34803]  
2     3       3/3            0.0.0.0:34802  [0.0.0.0:34803,0.0.0.0:34801]  
3     3       3/3            0.0.0.0:34803  [0.0.0.0:34802,0.0.0.0:34801]  
4     4       2/3            -              [0.0.0.0:34802,0.0.0.0:34803]  
5     3       3/3            0.0.0.0:34802  [0.0.0.0:34801,0.0.0.0:34803]  
6     3       3/3            0.0.0.0:34803  [0.0.0.0:34801,0.0.0.0:34802]  
7     4       2/3            -              [0.0.0.0:34803,0.0.0.0:34802]  

node                 primary  secondary  total  
0.0.0.0:34801        0        5          5      
0.0.0.0:34802        2        6          8      
0.0.0.0:34803        3        5          8      
                     5        16         21     

fully_healthy_partition_count    : 5
unhealthy_partition_count        : 3
write_unhealthy_partition_count  : 3
read_unhealthy_partition_count   : 3

list app temp succeed
```

If you set this item to "min_live_node_count_for_unfreeze = 2":

```
>>> app temp -d
[Parameters]
app_name  : temp
detailed  : true

[Result]
app_name           : temp
app_id             : 1   
partition_count    : 8   
max_replica_count  : 3   
details            :     
pidx  ballot  replica_count  primary              secondaries            
0     4       2/3            0.0.0.0:34803  [0.0.0.0:34802]  
1     5       2/3            0.0.0.0:34802  [0.0.0.0:34803]  
2     4       2/3            0.0.0.0:34802  [0.0.0.0:34803]  
3     4       2/3            0.0.0.0:34803  [0.0.0.0:34802]  
4     5       2/3            0.0.0.0:34803  [0.0.0.0:34802]  
5     4       2/3            0.0.0.0:34802  [0.0.0.0:34803]  
6     4       2/3            0.0.0.0:34803  [0.0.0.0:34802]  
7     5       2/3            0.0.0.0:34802  [0.0.0.0:34803]  

node                 primary  secondary  total  
0.0.0.0:34802        4        4          8      
0.0.0.0:34803        4        4          8      
                     8        8          16     

fully_healthy_partition_count    : 0
unhealthy_partition_count        : 8
write_unhealthy_partition_count  : 0
read_unhealthy_partition_count   : 0

list app temp succeed
```

your cluster can still be able to read/write.

**Comment by qinzuoyan** [comment]
@jackeylove01 参见楼上neverchanje的解释，原来有3个replica-server，你kill掉一个后，只有两个了，就会进入freezed模式，这种模式下会禁止所有的config更新，所以无法切换新的primary。你可以在shell中执行`cluster_info`命令 ，可以看到meta_function_level是freezed。
