### ISSUE TITLE
有怎么编译的说明吗？

### ISSUE THREAD

**Issue by liudf0716** [XiaoMi/pegasus#4]
run.sh build 不行
cd src
cmake ..

![image](https://user-images.githubusercontent.com/1182593/31933479-ce8687d2-b8db-11e7-8966-44d116e598d4.png)

**Comment by shengofsun** [comment]
目前直接调用用cmake是不能编译的，随着后面的重构这一点可能改进下。

是按[编译](https://github.com/XiaoMi/pegasus/wiki/%E7%BC%96%E8%AF%91%E6%9E%84%E5%BB%BA)的做法吗？出什么问题了？可以给个截图么？

注意拖代码的时候要把rdsn这个submodule也拖下来的。

**Comment by liudf0716** [comment]
截图好像提不上去，建议把编译这块搞的详细点，我稍微试了几下，无论是setup.sh的脚本，以及cmake的方式。

**Comment by liudf0716** [comment]
编译文档写的挺详细的，可惜是github下载的时候下不动。

**Comment by shengofsun** [comment]
主要是从github上拖第三方库不太友好，后面我们会把第三方库的下载和编译过程抽出来，到时候也可以考虑换个下载起来块的镜像。

**Comment by Allianzcortex** [comment]
@shengofsun  build standalone cluster on laptop ubuntu 14.04 LTS successful~~~

**Comment by qinzuoyan** [comment]
@liudf0716 ，yes you are right, the download speed from github is badly slow. We are considering some solution to make it faster and more friendly.

**Comment by shengofsun** [comment]
@liudf0716 @Allianzcortex 
现在第三方依赖的下载在单独的脚本[rdsn/thirdparty/download-thirdparty.sh](https://github.com/XiaoMi/rdsn/blob/master/thirdparty/download-thirdparty.sh)中进行。
在编译的时候不用指定-g选项了。
依赖下载现在也只下载压缩包，而不用clone整个依赖的repo，下载速度应该有很大的提升。
另外欢迎加入我们的[slack讨论群](https://join.slack.com/t/pegasus-kv/shared_invite/enQtMjcyMjQzOTk4Njk1LWVkMjlkMGE5Mzg1Y2M3MDc0NGYyYzQ5YzYyMGE0ZjlhMDMyNjU1ZGViYzdjZmUwNjVmNGE0ZDdkMWJiN2Q1MDY)

**Comment by Allianzcortex** [comment]
@shengofsun 我在进入 slack 时提示我的邮箱(iamwanghz@gmail.com) No account found？需要把我加入到名单列表中吗？

**Comment by 31737951** [comment]
In file included from /home/x/pegasus/src/server/info_collector.cpp:5:0:
/home/x/pegasus/src/server/info_collector.h:15:20: fatal error: evhttp.h: 没有那个文件或目录
 #include <evhttp.h>
                    ^
compilation terminated.
server/CMakeFiles/pegasus_server.dir/build.make:86: recipe for target 'server/CMakeFiles/pegasus_server.dir/info_collector.cpp.o' failed
make[2]: *** [server/CMakeFiles/pegasus_server.dir/info_collector.cpp.o] Error 1
CMakeFiles/Makefile2:308: recipe for target 'server/CMakeFiles/pegasus_server.dir/all' failed
make[1]: *** [server/CMakeFiles/pegasus_server.dir/all] Error 2
make[1]: *** 正在等待未完成的任务....

**Comment by 31737951** [comment]
编译的时候出了个错误,环境 ububtu ,按照编译说明来的

还有 ,哥们,能不能出个编译好的,建个编译好的环境实在是麻烦

出个预览版本也不错啊,大家可以先使用上有个初步认识

**Comment by 31737951** [comment]
gcc (Ubuntu 6.3.0-12ubuntu2) 6.3.0 20170406
cmake version 3.7.2
/usr/lib/x86_64-linux-gnu/libboost_random.so.1.62.0

其他的安装是
sudo apt-get install build-essential cmake libboost-all-dev libaio-dev libsnappy-dev libbz2-dev libreadline-dev libgflags-dev zlib1g zlib1g.dev

**Comment by shengofsun** [comment]
@31737951 看上去像是第三方库没有下载安装完成，建议先到rdsn/thirdparty下，清除build src output目录， 执行download-thirdparty.sh和build-thirdparty.sh，再回根目录编译。

**Comment by 31737951** [comment]
发现两个问题
1.编译protobuf 时候生成的脚本有问题
2. https://codeload.github.com/libevent/libevent/tar.gz/release-2.0.22-stab 已经失效了

**Comment by 31737951** [comment]
cmake_install.cmake:650 
file INSTALL cannot find
  "/home/x/pegasusmast/rdsn/thirdparty/build/protobuf//home/x/pegasusmast/rdsn/thirdparty/output/lib/cmake/protobuf".

这个地方的路径生成错误了,修改正确后就可以编译过了
make -j8 && make install

**Comment by 31737951** [comment]
哥们,编译完毕了想吧部署包剔除来,请问下主要是那些文件或者目录

**Comment by shengofsun** [comment]
@31737951 可以参考./run.sh start_onebox的命令是怎么起集群的，也可以参考scripts/pack_server.sh

**Comment by shengofsun** [comment]
@31737951 欢迎加到我们的[slack讨论群](https://join.slack.com/t/pegasus-kv/shared_invite/enQtMjcyMjQzOTk4Njk1LWVkMjlkMGE5Mzg1Y2M3MDc0NGYyYzQ5YzYyMGE0ZjlhMDMyNjU1ZGViYzdjZmUwNjVmNGE0ZDdkMWJiN2Q1MDY)里面

**Comment by 31737951** [comment]
给后面的人补充下 centos下编译
* 编译说明上有点问题 GCC 4.8.2是编译不过的，目前7下面update下可以升级到 4.8.5 是可以编译过的
