### ISSUE TITLE
build question

### ISSUE THREAD

**Issue by mysunnyshine** [XiaoMi/pegasus#407]
the error is showed in the picture
cmake 2.8.12
os:   Centos 7.2
![image](https://user-images.githubusercontent.com/24480430/67266772-92410900-f4e3-11e9-881b-11e54142002d.png)

**Comment by neverchanje** [comment]
your cmake version is too old, use >=3.5.2.

**Comment by vagetablechicken** [comment]
这是fds编译时没有找到gtest的lib，建议查一下[$TP_OUTPUT/lib](https://github.com/XiaoMi/rdsn/blob/master/thirdparty/build-thirdparty.sh#L213)里有没有gtest的lib。
thirdparty编译只要求cmake>=2.8，但我们的pegasus要求cmake>=3.5.2，还是需要你升级cmake

**Comment by mysunnyshine** [comment]
> 这是fds编译时没有找到gtest的lib，建议查一下[$TP_OUTPUT/lib](https://github.com/XiaoMi/rdsn/blob/master/thirdparty/build-thirdparty.sh#L213)里有没有gtest的lib。
> thirdparty编译只要求cmake>=2.8，但我们的pegasus要求cmake>=3.5.2，还是需要你升级cmake

ok, I will try
