### ISSUE TITLE
periodic memory release results in increased latency

### ISSUE THREAD

**Issue by Shuo-Jia** [XiaoMi/pegasus#408]
## Pegasus version
pegasus-server-1.11.6-9f4e5ae-glibc2.12-release
## Problem
periodic memory release results in increased latency
## Reason
When build and  run  rdsn，the macro `ENABLE_GPERF`  and  the variable `mem_release_enabled`default value is `ON`:
```
#ifdef DSN_ENABLE_GPERF
    if (_options.mem_release_enabled) {
        _mem_release_timer_task =
            tasking::enqueue_timer(LPC_MEM_RELEASE,
                                   &_tracker,
                                   []() {
                                       ddebug("Memory release has started...");
                                       ::MallocExtension::instance()->ReleaseFreeMemory();
                                       ddebug("Memory release has ended...");
                                   },
                                   std::chrono::milliseconds(_options.mem_release_interval_ms),
                                   0,
                                   std::chrono::milliseconds(_options.mem_release_interval_ms));
    }
#endif
```
but the strategies for freeing memory is unreasonable. for example, this time frees too much memory (5GB) at once  and results in the significant latency.
## Solution
Now the config.ini is not set the value about "release memory", we can only add the section and set the `mem_release_enabled` value is false.

**Comment by neverchanje** [comment]
This problem is resolved in [v1.12.1](https://github.com/XiaoMi/pegasus/releases/tag/v1.12.1). Refer to this PR: https://github.com/XiaoMi/rdsn/pull/343.
