### ISSUE TITLE
git clone --resursive failed

### ISSUE THREAD

**Issue by mysunnyshine** [XiaoMi/pegasus#412]
## General Question

Before asking a question, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/XiaoMi/pegasus/issues)
- Read the documentation:
  - [Pegasus Doc](https://pegasus-kv.github.io)

![image](https://user-images.githubusercontent.com/24480430/67917623-8ab0ec80-fbd4-11e9-956d-a68c609d5c88.png)

**Comment by neverchanje** [comment]
You can clone rdsn origin/master on your pegasus directory.

```
cd pegasus/
https://github.com/XiaoMi/rdsn.git
```

**Comment by mysunnyshine** [comment]
> You can clone rdsn origin/master on your pegasus directory.
> 
> ```
> cd pegasus/
> git clone https://github.com/XiaoMi/rdsn.git
> ```
Os: CentOS7
Cmake: 3.10
Gcc:  8.0

Now,  anthoer question is as below:

![image](https://user-images.githubusercontent.com/24480430/67921227-0e250a80-fbe2-11e9-94a9-15c21effe3f7.png)

**Comment by mysunnyshine** [comment]
> You can clone rdsn origin/master on your pegasus directory.
> 
> ```
> cd pegasus/
> git clone https://github.com/XiaoMi/rdsn.git
> ```

![image](https://user-images.githubusercontent.com/24480430/67921284-37459b00-fbe2-11e9-8b86-5e3d292c8c0e.png)

**Comment by mysunnyshine** [comment]
> You can clone rdsn origin/master on your pegasus directory.
> 
> ```
> cd pegasus/
> git clone https://github.com/XiaoMi/rdsn.git
> ```
![image](https://user-images.githubusercontent.com/24480430/67921331-547a6980-fbe2-11e9-84e9-560b6345f6f8.png)

**Comment by neverchanje** [comment]
This is the problem of zookeeper c client, not of Pegasus. You can use an older version GCC.
