### ISSUE TITLE
Need to init environment variables before the unit test

### ISSUE THREAD

**Issue by Smityz** [XiaoMi/pegasus#418]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
When I made a unit test,it reported
```
./run.sh: 7: ./run.sh: ./clear.sh: Permission denied
./dsn.replica.test: error while loading shared libraries: libPocoCrypto.so.48: cannot open shared object file: No such file or directory
```
2. What did you expect to see?
I should set environment variables before the unit test.
```
export LD_LIBRARY_PATH=~/code/pegasus/rdsn/thirdparty/output/lib/:$LD_LIBRARY_PATH
```

**Comment by vagetablechicken** [comment]
clean & build thirdparty(poco&fds)
