### ISSUE TITLE
pegasus meta 进程内存泄露

### ISSUE THREAD

**Issue by sunwsh** [XiaoMi/pegasus#429]
## Bug Report
最近看到pegasus meta 的primary进程内存一直在增长， 
版本： v1.11.1 

用pmap 看到
root@iZwz9a47t80hnkbpiuyzoeZ:/proc/29363# pmap -d 29363
29363:   ./pegasus_server config_meta.ini -app_list meta
Address           Kbytes Mode  Offset           Device    Mapping
0000000000400000    7004 r-x-- 0000000000000000 0fd:00010 pegasus_server
0000000000cde000     112 rw--- 0000000000000000 000:00000   [ anon ]
0000000001f58000 11359232 rw--- 0000000000000000 000:00000   [ anon ]

用valgrind --tool=memcheck --leak-check=yes --show-reachable=yes --run-libc-freeres=yes --log-file=./valgrind_report.log ./pegasus_server  config.ini -app_list meta 
==26730== Mismatched free() / delete / delete []
==26730==    at 0x4C2EF90: free (vg_replace_malloc.c:540)
==26730==    by 0x5EA5719: deallocate (new_allocator.h:110)

非常多Mismatched free，
==26730== HEAP SUMMARY:
==26730==     in use at exit: 35,786,093 bytes in 61,548 blocks
==26730==   total heap usage: 118,319 allocs, 56,771 frees, 86,003,342 bytes allocated
==26730== 
==26730== LEAK SUMMARY:
==26730==    definitely lost: 2,477 bytes in 51 blocks
==26730==    indirectly lost: 4,288 bytes in 90 blocks
==26730==      possibly lost: 89,490 bytes in 253 blocks
==26730==    still reachable: 35,689,838 bytes in 61,154 blocks
==26730==                       of which reachable via heuristic:
==26730==                         newarray           : 18,752 bytes in 1 blocks
==26730==         suppressed: 0 bytes in 0 blocks
==26730== Rerun with --leak-check=full to see details of leaked memory
==26730== 
==26730== For lists of detected and suppressed errors, rerun with: -s
==26730== ERROR SUMMARY: 49352 errors from 1000 contexts (suppressed: 0 from 0)

**Comment by acelyc111** [comment]
Fixed by https://github.com/XiaoMi/rdsn/pull/477
