### ISSUE TITLE
http url中含有‘#’的处理问题

### ISSUE THREAD

**Issue by levy5307** [XiaoMi/pegasus#440]
在http请求中，'#'之后的部分叫做锚部分，该部分代表网页中的一个位置，用于浏览器读取这个url后，自动滚动到锚部分指定的区域。

由于锚部分是用来指导浏览器动作的，对服务器完全无用，所以HTTP请求中不会包含锚部分，也就是说，会将其截断、不发送给服务器。

目前我们有一个http接口，用于获取perf counter信息，例如：
```http://127.0.0.1:34101/perfCounter?name=collector*app.pegasus*app.stat.read_qps#_all_```用于获取名字为 `collector*app.pegasus*app.stat.read_qps#_all_`的perf counter信息，但是由于该名字中包含了‘#’，所以会将#_all_这部分截断，服务器获取到的请求就变成了```http://127.0.0.1:34101/perfCounter?name=collector*app.pegasus*app.stat.read_qps```，导致无法获取正确的perf counter信息。

目前我想到的办法是:
1.对用户端发出的请求和服务端收到的请求添加编解码，对这种特殊字符进行转义。
2.实现http_message_parser中对header部分的解析，将name={perf_counter_name}放到header部分中

1是比较常规的做法，业内对于传递特殊字符都需要编解码。2这里感觉也比较有必要，因为目前我们的http实现不健全，对于header和body部分都没有实现读取

**Comment by acelyc111** [comment]
`name=collector*app.pegasus*app.stat.read_qps#_all_`
其实根本原因是我们的perf counter名字太诡异了，包含各种符号，后面的思路应该是怎么去优化名字的规则

**Comment by levy5307** [comment]
> `name=collector*app.pegasus*app.stat.read_qps#_all_`
> 其实根本原因是我们的perf counter名字太诡异了，包含各种符号，用户是难以记忆的，后面的思路应该是怎么去优化名字的规则

名字诡异确实是一方面，但是uri编解码也是必要的

**Comment by neverchanje** [comment]
This problem was solved by https://github.com/XiaoMi/rdsn/pull/357, reopen it when there is futher issue.
