### ISSUE TITLE
Pegasus编译出错

### ISSUE THREAD

**Issue by mago960806** [XiaoMi/pegasus#5]
![image](https://user-images.githubusercontent.com/18606660/32086773-0e422f36-bb0a-11e7-975a-94709618b3f8.png)

**Comment by qinzuoyan** [comment]
你的cmake版本是？

**Comment by mago960806** [comment]
cmake version 2.8.12.2

**Comment by qinzuoyan** [comment]
重新用这个命令试试？
 ./run.sh build -g github -c

**Comment by mago960806** [comment]
![image](https://user-images.githubusercontent.com/18606660/32141435-36c392bc-bcbb-11e7-8195-90056b024cf9.png)
感谢！加-c参数之后就编译成功了！
