### ISSUE TITLE
unit test lost_log.slog failed

### ISSUE THREAD

**Issue by acelyc111** [XiaoMi/pegasus#555]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
`./run.sh test`

2. What did you expect to see?
All tests should passed

3. What did you see instead?
lost_log.slog test failed, one of replica server core dumped with output:
```
E2020-06-29 00:10:00.681 (1593360600681081538 6f00) replica.default0.00006eb700010001: mutation_log.cpp:1999:read_next_log_block(): read data block body failed, size = 77 vs 613, err = ERR_HANDLE_EOF
F2020-06-29 00:10:00.687 (1593360600687823243 6f00) replica.default0.00006eb700010001: replica_stub.cpp:604:initialize(): assertion expression: smax == pmax
F2020-06-29 00:10:00.687 (1593360600687852372 6f00) replica.default0.00006eb700010001: replica_stub.cpp:604:initialize(): 2.1@10.132.7.51:34801: some shared log state must be lost, smax(2697) vs pmax(22252)
```

4. What version of Pegasus are you using?
The latest version(cdda746e05bbbae6b49d36eb7afce611d4f5ea25, rdsn: c9944f3901dffc9e2a2bd5cd80117e5111eb558e)

**Comment by levy5307** [comment]
Resolved in https://github.com/XiaoMi/rdsn/pull/519
