### ISSUE TITLE
从Rocksdb导入数据无法转移

### ISSUE THREAD

**Issue by mzss0** [XiaoMi/pegasus#558]
## General Question

Before asking a question, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/XiaoMi/pegasus/issues)
- Read the documentation:
  - [Pegasus Doc](https://pegasus-kv.github.io)

通过rocksdb导入sst文件成功了并且能从pegasus查到，但是新的replica不能通过learn获取到rocksdb导入的数据

唯一尝试成功转移的方法是调用远程kill命令，这个命令在每个分片replica重启后会生成checkpoint。但是我直接生成checkpoint并不能转移。我看了learn相关文档和代码，试了flush mem等很多操作，也没成功。请问要怎么绕开kill来实现这个功能？

**Comment by acelyc111** [comment]
"通过rocksdb导入sst文件" 这个你是怎么做的呢？
这个功能 [bulkload](https://pegasus-kv.github.io/2020/02/18/bulk-load-design.html) 我们还在开发中

**Comment by mzss0** [comment]
> "通过rocksdb导入sst文件" 这个你是怎么做的呢？
> 这个功能 [bulkload](https://pegasus-kv.github.io/2020/02/18/bulk-load-design.html) 我们还在开发中

就是rocksdb的一个方法，可以导入数据，跟你们那个文档一样

**Comment by acelyc111** [comment]
在当前版本的Pegasus实现中，新数据的写入会更新decree，并记录到rocksdb的manifest中。这是一个我们在原生rocksdb上新增的字段。我怀疑ingest sst的时候并没有更新decree，其他replica自然也learn不到这部分新增的数据。

**Comment by mzss0** [comment]
> 在当前版本的Pegasus实现中，新数据的写入会更新decree，并记录到rocksdb的manifest中。这是一个我们在原生rocksdb上新增的字段。我怀疑ingest sst的时候并没有更新decree，其他replica自然也learn不到这部分新增的数据。

有更新这个decree的参考嘛，我试过直接更新lastcommitdecree，就是直接做一个＋＋，就像写入的时候一样，但是会coredump

**Comment by acelyc111** [comment]
> > 在当前版本的Pegasus实现中，新数据的写入会更新decree，并记录到rocksdb的manifest中。这是一个我们在原生rocksdb上新增的字段。我怀疑ingest sst的时候并没有更新decree，其他replica自然也learn不到这部分新增的数据。
> 
> 有更新这个decree的参考嘛，我试过直接更新lastcommitdecree，就是直接做一个＋＋，就像写入的时候一样，但是会coredump
> 
> 还有能解答一下为什么用远程命令kill之后产生的checkpoint能正常转移而我直接生成的不行，这里面能加代码实现功能吗

没有看到具体的代码，还真不清楚具体是哪里的问题。
你可以等等我们官方支持的bulk load，1~2周内就会发RC版本了。
