### ISSUE TITLE
ubuntu 18.04  run.sh build -c error

### ISSUE THREAD

**Issue by totalo** [XiaoMi/pegasus#562]
ubuntu 18.04  run.sh build -c error

`./autogen.sh: 18: ./autogen.sh: aclocal: not found
./build-thirdparty.sh: line 145: ./configure: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
build libevent failed
ERROR: build rdsn failed`

**Comment by acelyc111** [comment]
Have you installed all dependent libs and tools? https://pegasus-kv.github.io/overview/compilation

**Comment by totalo** [comment]
> dependent

Yeah! I think i've solved it! I chechked the version and install them again,but a new error is here.


`Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
ERROR: build pegasus failed
ERROR: build pegasus failed
`

**Comment by totalo** [comment]
All right !  I've build success! it's seem to be loss gtest.
