### ISSUE TITLE
unexpected low qps on ssd machine, any thing wrong?

### ISSUE THREAD

**Issue by secwang** [XiaoMi/pegasus#7]
Init pegasus succeed
LevelDB:    version 4.0
Date:       Thu Nov  9 08:13:07 2017
CPU:        2 * Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz
CPUCache:   46080 KB
Keys:       16 bytes each
Values:     100 bytes each (100 bytes after compression)
Entries:    100000
Prefix:    0 bytes
Keys per prefix:    0
RawSize:    11.1 MB (estimated)
FileSize:   11.1 MB (estimated)
Writes per second: 0
Compression: NoCompression
Memtablerep: skip_list
Perf Level: 0
WARNING: Optimization is disabled: benchmarks unnecessarily slow
WARNING: Assertions are enabled; benchmarks unnecessarily slow

Thread  Count   Runtime QPS     AvgLat  P99Lat
1       10000   11.763  850     1176    2425
2       20000   20.256  987     2018    4953
3       30000   29.534  1015    2938    7817
4       40000   38.809  1030    3765    12794

**Comment by qinzuoyan** [comment]
Is it read or write? The result shows that the average latency is in range of [1,4] milliseconds, depending on the thread count.
These aspects may improve performance:
- build with -t release option
- use SSD instead of HDD

**Comment by secwang** [comment]
build with -t release, Thanks.
Thread Count Runtime QPS AvgLat P99Lat
1 10000 4.9163 2033 491 1377
2 20000 8.1208 2462 808 2443
3 30000 11.623 2580 1153 3607
4 40000 15.369 2602 1517 5742
5 50000 19.670 2541 1937 7728
