### ISSUE TITLE
build时出现Not a git repository: ../.git/modules/rdsn 错误

### ISSUE THREAD

**Issue by qinhongsheng** [XiaoMi/pegasus#8]
环境
CentOS 7.3.1611
kernel 3.10.0-514.el7.x86_64
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16)
cmake 2.8.12.2
boost 1.53.0 Release 27.el7

参考：
https://github.com/XiaoMi/pegasus/blob/master/docs/installation.md

1、安装开发包
yum -y install cmake boost-devel libaio-devel snappy-devel bzip2-devel 
readline-devel
2、clone
3、build

日志如下：
ln: failed to create symbolic link ‘/root/pegasus/DSN_ROOT’: File exists
INFO: start build rdsn...
CLEAR=NO
BUILD_TYPE=debug
SERIALIZE_TYPE=
GIT_SOURCE=github
ONLY_BUILD=YES
RUN_VERBOSE=NO
WARNING_ALL=NO
ENABLE_GCOV=NO
Use system boost
CMAKE_OPTIONS= -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ 
-DCMAKE_BUILD_TYPE=Debug -DDSN_GIT_SOURCE=github
MAKE_OPTIONS= -j8
#############################################################################
fatal: Not a git repository: ../.git/modules/rdsn

**Comment by shengofsun** [comment]
稍等，我看一下，可能是最近提交的时候子项目的索引没注意

**Comment by shengofsun** [comment]
@qinhongsheng clone的时候是不是没有指定--recursive参数？

**Comment by shengofsun** [comment]
@qinhongsheng 我建了一个[slack讨论群](https://join.slack.com/t/pegasus-kv/shared_invite/enQtMjcyMjQzOTk4Njk1LWVkMjlkMGE5Mzg1Y2M3MDc0NGYyYzQ5YzYyMGE0ZjlhMDMyNjU1ZGViYzdjZmUwNjVmNGE0ZDdkMWJiN2Q1MDY)，欢迎进行进一步交流

**Comment by quanzl** [comment]
已确认是 git clone 后的文件夹不完整导致，可能是网络原因引起。

删除整个 pegasus，重新尝试，目前已经正常。

**Comment by qinzuoyan** [comment]
OK, Thanks.
