### ISSUE TITLE
文档未提及CentOS7平台的一点补充

### ISSUE THREAD

**Issue by quanzl** [XiaoMi/pegasus#9]
需要两个文档未提及的包
1、zlib-devel
编译时需要，否则出错
2、nmap-ncat
没有这个会在 ./run.sh start_onebox 这一步骤遇到：
./scripts/start_zk.sh: line 62: nc: command not found

目前编译完成，还在继续作新手尝试。

感谢各位开发者的贡献。

**Comment by qinzuoyan** [comment]
Thanks for your contribution.

**Comment by quanzl** [comment]
继续补充，编译过程对内存还是有一点要求的，因为用的是macOS，编译环境用的是1G内存的虚拟机。编译过程很慢，硬盘狂闪，可能有大量的页交换，最后终于 outofmemory。
增加虚拟机内存至4G，编译可以顺利进行。

**Comment by qinzuoyan** [comment]
是的，因为C++使用了大量的模板、lambda函数等特性，编译本来就比较耗资源，同时又默认开启并行编译，所以对资源的要求还挺高的。

**Comment by quanzl** [comment]
目录下有一个 java，这里边并不包含 jvm，不要被它骗了。
如果没有安装 java，zookeeper启动仍然会提示：
Starting zookeeper ... STARTED
其实并没有

随后 nc 会报错，但是启动过程也没有停止，虽然最后看起来启动成功，仍然是连不上的，安装
yum install java-1.8.0-openjdk
这一关就通过了，zkServer.sh start-foreground 会成功，nc 测试通过。

**Comment by shengofsun** [comment]
@quanzl 感谢反馈，我们后续会把这些加入到文档中

**Comment by quanzl** [comment]
@shengofsun 做点微薄贡献，希望对别人有点帮助。

最后补充：
1、启东时：
Ncat: Connection refused.
ERROR: start zookeeper failed
这个没有影响，猜测是启动需要时间，nc等待间隔过短引起，物理机上可能没有这个问题。
2、命令行工具
 ./run.sh shell 启动过程有点慢，也许是虚拟机的原因，多等待一会儿就能看到命令提示符。

感谢支持。
